## Chapter 5 
### Array-Based Sequences

1)  Write a program that can perform the Caesar cipher for English messages
    that include both upper- and lowercase characters.

In [ ]:
#A Caesar cipher is a simple method of encoding messages. Caesar ciphers use a substitution method where letters 
#in the alphabet are shifted by some fixed number of spaces to yield an encoding alphabet.

In [1]:
#Let us try to cipher the string "Python is fun"

l_shift = 3
#this means our alphabet will shift by 3, so, A --> D B --> E and so on...

def encrypt(text,l_shift):
    result = ""
   # transverse the plain text
    for i in range(len(text)):
        char = text[i]
      # Encrypt uppercase characters in plain text
        if (char.isupper()):
         result += chr((ord(char) + l_shift-65) % 26 + 65)
      # Encrypt lowercase characters in plain text
        else:
         result += chr((ord(char) + l_shift - 97) % 26 + 97)
    return result

text = "Python is fun"
codatext = encrypt(text,l_shift)
print("Original text is: ", text)
print("Ceaser Coded Text is: ", codatext )

Original text is:  Python is fun
Ceaser Coded Text is:  Sbwkrqqlvqixq


2) Write a Python function that takes two three-dimensional numeric data
sets and adds them componentwise.

In [4]:
import numpy as np

def add_3d_datasets(dataset1, dataset2):
    """
    Adds two three-dimensional numeric datasets componentwise.

    Parameters:
    - dataset1: numpy array, shape (m, n, p)
    - dataset2: numpy array, shape (m, n, p)

    Returns:
    - result: numpy array, shape (m, n, p), componentwise sum of the input datasets
    """
    # Check if the shapes of the datasets are the same
    if dataset1.shape != dataset2.shape:
        raise ValueError("Input datasets must have the same shape.")

    # Perform componentwise addition
    result = dataset1 + dataset2

    return result
import numpy as np

# Creating two example three-dimensional datasets
dataset1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

dataset2 = np.array([[[2, 3, 4], [5, 6, 7], [8, 9, 10]],
                     [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                     [[20, 21, 22], [23, 24, 25], [26, 27, 28]]])

# Call the function to add the datasets
result = add_3d_datasets(dataset1, dataset2)

print("Dataset 1:")
print(dataset1)

print("\nDataset 2:")
print(dataset2)

print("\nComponentwise Sum:")
print(result)



Dataset 1:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Dataset 2:
[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]

Componentwise Sum:
[[[ 3  5  7]
  [ 9 11 13]
  [15 17 19]]

 [[21 23 25]
  [27 29 31]
  [33 35 37]]

 [[39 41 43]
  [45 47 49]
  [51 53 55]]]
